title: "10年ちょっとやってきた僕のアジャイル開発の現在地"
summary: "僕がシニアエンジニアとしてどのようにアジャイル開発を実践しているかの現在地を紹介します。アジャイルな開発に取り組んでいるみなさんにとって何かしら、ヒントや刺激になるようなものがあると嬉しいです。"
topics: ["Agile"]
published: false
price: 0
chapters:
  - introduction
  - value
  - iteration
  - team
  - role
  - discovery
  - planning
  - development
  - organization
  - outro
